spring:
  cloud:
    bus:
      enabled: false
management:
  health:
    rabbit:
      enabled: false
gateway-base-url: http://localhost:8080
feign:
  url:
    gateway: test
    auth: test
    shop: test
