spring:
  cloud:
    openfeign:
      client:
        config:
          auth-service:
            url: http://localhost:8081
          shop-service:
            url: http://localhost:8080
server:
  port: 8082
