gateway-base-url: https://ink3.shop/dev/gateway
server:
  servlet:
    context-path: /dev
feign:
  url:
    auth: https://ink3.shop/dev/gateway/auth
    shop: https://ink3.shop/dev/gateway/shop
auth:
  protected-paths:
    - /me/*

toss:
  url:
    success: http://localhost:8080/dev/payments/success
    fail: http://localhost:8080/dev/payments/fail