gateway-base-url: http://localhost:8081
spring:
  cloud:
    openfeign:
      client:
        config:
          auth-service:
            url: http://localhost:8081/auth
          shop-service:
            url: http://localhost:8081/shop
server:
  port: 8080
