name: Deploy Frontend To Dev

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Linux Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21


      - name: Build JAR (skip tests)
        run: mvn package -DskipTests=true -B

      - name: Verify JAR file
        run: ls -lh target/*.jar

      - name: Extract version from POM
        id: extract_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 추출된 버전 확인
        run: echo "${{ steps.extract_version.outputs.version }} 입니다."

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_IP }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          source: "target/*.jar"
          target: "~/ink3-server-dev/front-dev"

      - name: Run deploy.sh on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/ink3-server-dev/front-dev
            chmod +x deploy.sh
            export RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }}
            export RABBITMQ_PORT=${{ secrets.RABBITMQ_PORT }}
            export RABBITMQ_USERNAME=${{ secrets.RABBITMQ_USERNAME }}
            export RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}
            nohup ./deploy.sh "${{ steps.extract_version.outputs.version }}" > deploy.log 2>&1 &
            exit 0
